services:
  mensa-bot:
    build: .
    container_name: polito-mensa-bot
    restart: unless-stopped
    user: "1000:1000"
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      TARGET_USER: ${TARGET_USER}
      TZ: "Europe/Rome"
    volumes:
      - ./data:/workspace/data
